family:
  family-name: "happy family"
  father: "jack"
  mother: "rose"
  child: "tom"

person:
  name: dongfei
  age: 20
  happy: false
  birth: 2001/01/01
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - girl
    - music
  dog:
    name: 虎子
    age: 11